server:
  http-port: 54321
  port: 12345
  ssl:
    enabled: true
    key-store: keystore.jks
    key-store-password: P@ssw0rd
    keyStoreType: PKCS12

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your_client_id
            client-secret: your_client_secret
          google:
            client-id: your_client_id
            client-secret: your_client_secret
          facebook:
            client-id: your_client_id
            client-secret: your_client_secret
          line:
            provider: line
            client-id: your_client_id
            client-secret: your_client_secret
            client-authentication-method: client_secret_basic
            client-name: Line
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - openid+email
          apple:
            provider: apple
            client-id: your-apple-client-id
            client-secret: your-apple-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub

